# Generated by Django 3.0.2 on 2020-02-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='username',
        ),
    ]
