# Generated by Django 3.0.2 on 2020-02-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0002_auto_20200203_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='phone',
        ),
        migrations.AlterField(
            model_name='logintable',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
