# Generated by Django 3.0.2 on 2020-03-04 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ret1name', models.CharField(max_length=200)),
                ('ret1info', models.CharField(default='Nothing much', max_length=1000)),
                ('ret2name', models.CharField(default='No Product', max_length=200)),
                ('ret2info', models.CharField(default='Nothing much', max_length=1000)),
                ('ret3name', models.CharField(default='No Product', max_length=200)),
                ('ret3info', models.CharField(default='Nothing much', max_length=1000)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsapp.Product')),
            ],
        ),
    ]
