# Generated by Django 3.0.2 on 2020-03-06 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0007_product_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
