# Generated by Django 3.0.2 on 2020-03-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0008_product_product_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout1price', models.IntegerField(default=0)),
                ('layout2price', models.IntegerField(default=0)),
                ('layout3price', models.IntegerField(default=0)),
            ],
        ),
    ]
