# Generated by Django 3.0.2 on 2020-03-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0009_layoutprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(max_length=20)),
                ('totalamount', models.IntegerField(default=0)),
                ('startingdate', models.DateField()),
                ('endingdate', models.DateField()),
                ('adsimage', models.ImageField(upload_to='')),
                ('logintable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsapp.LoginTable')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsapp.Product')),
            ],
        ),
    ]
