# Generated by Django 3.0.2 on 2020-03-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0010_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='isactive',
            field=models.BooleanField(default=False),
        ),
    ]
