# Generated by Django 3.0.2 on 2020-03-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0012_product_about_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='about_user',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='about_user',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
