# Generated by Django 3.0.2 on 2020-03-22 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0015_logintable_lcoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_status', models.BooleanField(default=False)),
                ('prd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsapp.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsapp.LoginTable')),
            ],
        ),
    ]
