# Generated by Django 3.0.2 on 2020-03-29 04:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0016_favouriteproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='obsapp.Product')),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='obsapp.LoginTable')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsapp.LoginTable')),
            ],
        ),
        migrations.CreateModel(
            name='Pigeons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualmessage', models.CharField(max_length=2000)),
                ('messagetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('messageseen', models.BooleanField(default=False)),
                ('chatlists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsapp.Chatlists')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsapp.LoginTable')),
            ],
        ),
    ]
