# Generated by Django 3.0.2 on 2020-03-30 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0017_chatlists_pigeons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pigeons',
            name='chatlists',
        ),
        migrations.RemoveField(
            model_name='pigeons',
            name='user_id',
        ),
        migrations.AddField(
            model_name='pigeons',
            name='product_id',
            field=models.ForeignKey(blank=True, default=8, on_delete=django.db.models.deletion.CASCADE, to='obsapp.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pigeons',
            name='receiver_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='obsapp.UserInformation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pigeons',
            name='sender_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='obsapp.UserInformation'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Chatlists',
        ),
    ]
