# Generated by Django 3.0.2 on 2020-04-01 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0018_auto_20200330_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withwhatproduct', models.CharField(max_length=50)),
                ('is_request', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_responded', models.BooleanField(default=False)),
                ('datetimeofrequest', models.DateTimeField(default=datetime.datetime(2020, 4, 1, 16, 30, 58, 251633))),
                ('fromwhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromwhom', to='obsapp.UserInformation')),
                ('towhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsapp.UserInformation')),
                ('whatproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsapp.Product')),
            ],
        ),
    ]
