# Generated by Django 3.0.2 on 2020-04-01 11:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0019_requestexchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestexchange',
            name='datetimeofrequest',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 16, 37, 22, 211332)),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationtext', models.CharField(max_length=1000)),
                ('notificationtime', models.DateTimeField(default=datetime.datetime(2020, 4, 1, 16, 37, 22, 212333))),
                ('notificationseen', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsapp.UserInformation')),
            ],
        ),
    ]
