# Generated by Django 3.0.2 on 2020-04-17 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0024_auto_20200407_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('action', 'action'), ('puzzle', 'puzzle'), ('fun games', 'fun games')], default='puzzle', max_length=50)),
                ('aboutgame', models.CharField(max_length=2000)),
                ('gameiconimg', models.ImageField(upload_to='')),
                ('gamewallpaperimg', models.ImageField(upload_to='')),
                ('kingofgame', models.CharField(default='Still Waiting', max_length=100)),
                ('totalplays', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='notificationz',
            name='notificationtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 21, 11, 47, 987333)),
        ),
        migrations.AlterField(
            model_name='requestexchange',
            name='datetimeofrequest',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 21, 11, 47, 986332)),
        ),
    ]
