# Generated by Django 3.0.2 on 2020-04-17 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0025_auto_20200417_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='htmlname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationz',
            name='notificationtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 21, 23, 17, 570765)),
        ),
        migrations.AlterField(
            model_name='requestexchange',
            name='datetimeofrequest',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 21, 23, 17, 569764)),
        ),
    ]
