# Generated by Django 3.0.2 on 2020-04-18 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0027_auto_20200417_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationz',
            name='notificationtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 11, 40, 48, 604995)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='typeofqst',
            field=models.CharField(choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD')], max_length=50),
        ),
        migrations.AlterField(
            model_name='requestexchange',
            name='datetimeofrequest',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 11, 40, 48, 602994)),
        ),
    ]
