# Generated by Django 3.0.2 on 2020-04-24 08:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0030_auto_20200422_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerating',
            name='reviewtime',
            field=models.DateField(default=datetime.datetime(2020, 4, 24, 13, 30, 12, 350777)),
        ),
        migrations.AlterField(
            model_name='notificationz',
            name='notificationtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 13, 30, 12, 345771)),
        ),
        migrations.AlterField(
            model_name='requestexchange',
            name='datetimeofrequest',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 13, 30, 12, 345771)),
        ),
        migrations.CreateModel(
            name='GamePlayed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startedgame', models.DateField(default=datetime.datetime(2020, 4, 24, 13, 30, 12, 352778))),
                ('gameid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsapp.Games')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsapp.LoginTable')),
            ],
        ),
    ]
