# Generated by Django 3.0.2 on 2020-06-19 18:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0032_auto_20200429_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayed',
            name='startedgame',
            field=models.DateField(default=datetime.datetime(2020, 6, 19, 23, 52, 27, 821715)),
        ),
        migrations.AlterField(
            model_name='gamerating',
            name='reviewtime',
            field=models.DateField(default=datetime.datetime(2020, 6, 19, 23, 52, 27, 820714)),
        ),
        migrations.AlterField(
            model_name='notificationz',
            name='notificationtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 23, 52, 27, 817712)),
        ),
        migrations.AlterField(
            model_name='requestexchange',
            name='datetimeofrequest',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 23, 52, 27, 816711)),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reson', models.CharField(max_length=2000)),
                ('resondate', models.DateField(default=datetime.datetime(2020, 6, 19, 23, 52, 27, 823716))),
                ('prd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsapp.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsapp.UserInformation')),
            ],
        ),
    ]
