# Generated by Django 3.0.2 on 2020-06-19 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0033_auto_20200619_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gameplayed',
            name='startedgame',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 0, 10, 51, 293279)),
        ),
        migrations.AlterField(
            model_name='gamerating',
            name='reviewtime',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 0, 10, 51, 291277)),
        ),
        migrations.AlterField(
            model_name='notificationz',
            name='notificationtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 0, 10, 51, 289276)),
        ),
        migrations.AlterField(
            model_name='report',
            name='resondate',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 0, 10, 51, 295280)),
        ),
        migrations.AlterField(
            model_name='requestexchange',
            name='datetimeofrequest',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 0, 10, 51, 288276)),
        ),
    ]
