# Generated by Django 3.0.2 on 2020-06-20 03:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0034_auto_20200620_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayed',
            name='startedgame',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 9, 10, 8, 305503)),
        ),
        migrations.AlterField(
            model_name='gamerating',
            name='reviewtime',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 9, 10, 8, 304503)),
        ),
        migrations.AlterField(
            model_name='notificationz',
            name='notificationtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 9, 10, 8, 302501)),
        ),
        migrations.AlterField(
            model_name='report',
            name='resondate',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 9, 10, 8, 307504)),
        ),
        migrations.AlterField(
            model_name='requestexchange',
            name='datetimeofrequest',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 9, 10, 8, 301500)),
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatmessage', models.CharField(max_length=2000)),
                ('messagetime', models.DateField(default=datetime.datetime(2020, 6, 20, 9, 10, 8, 299499))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsapp.UserInformation')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part1', to='obsapp.UserInformation')),
                ('participant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part2', to='obsapp.UserInformation')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsapp.Product')),
            ],
        ),
    ]
