# Generated by Django 3.0.2 on 2020-06-20 03:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0035_auto_20200620_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='chatroomid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='obsapp.ChatRoom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chats',
            name='messagetime',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 9, 18, 39, 970149)),
        ),
        migrations.AlterField(
            model_name='gameplayed',
            name='startedgame',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 9, 18, 39, 976154)),
        ),
        migrations.AlterField(
            model_name='gamerating',
            name='reviewtime',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 9, 18, 39, 976154)),
        ),
        migrations.AlterField(
            model_name='notificationz',
            name='notificationtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 9, 18, 39, 973151)),
        ),
        migrations.AlterField(
            model_name='report',
            name='resondate',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 9, 18, 39, 978156)),
        ),
        migrations.AlterField(
            model_name='requestexchange',
            name='datetimeofrequest',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 9, 18, 39, 972151)),
        ),
    ]
