# Generated by Django 3.0.2 on 2020-06-20 07:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0036_auto_20200620_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='messagetime',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 13, 11, 10, 808769)),
        ),
        migrations.AlterField(
            model_name='gameplayed',
            name='startedgame',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 13, 11, 10, 814771)),
        ),
        migrations.AlterField(
            model_name='gamerating',
            name='reviewtime',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 13, 11, 10, 813771)),
        ),
        migrations.AlterField(
            model_name='notificationz',
            name='notificationtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 13, 11, 10, 811769)),
        ),
        migrations.AlterField(
            model_name='report',
            name='resondate',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 13, 11, 10, 816773)),
        ),
        migrations.AlterField(
            model_name='requestexchange',
            name='datetimeofrequest',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 13, 11, 10, 810769)),
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_message', models.CharField(max_length=2000)),
                ('message_time', models.DateField(default=datetime.datetime(2020, 6, 20, 13, 11, 10, 817774))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsapp.UserInformation')),
            ],
        ),
    ]
