# Generated by Django 3.0.2 on 2020-06-20 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsapp', '0037_auto_20200620_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='messagetime',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 14, 28, 58, 91125)),
        ),
        migrations.AlterField(
            model_name='community',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 14, 28, 58, 100133)),
        ),
        migrations.AlterField(
            model_name='gameplayed',
            name='startedgame',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 14, 28, 58, 97131)),
        ),
        migrations.AlterField(
            model_name='gamerating',
            name='reviewtime',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 14, 28, 58, 96129)),
        ),
        migrations.AlterField(
            model_name='notificationz',
            name='notificationtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 14, 28, 58, 93126)),
        ),
        migrations.AlterField(
            model_name='report',
            name='resondate',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 14, 28, 58, 99132)),
        ),
        migrations.AlterField(
            model_name='requestexchange',
            name='datetimeofrequest',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 14, 28, 58, 93126)),
        ),
    ]
